//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BestEA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cart
    {
        public int cid { get; set; }
        public string OrderGuid { get; set; }
        public string Email { get; set; }
        public string PID { get; set; }
        public decimal PPrice { get; set; }
        public int Amont { get; set; }
        public string Sure { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
